"""Make user_credential.email unique

Revision ID: 13489110625c
Revises: 5468fe84a8c4
Create Date: 2025-08-27 00:10:30.225241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13489110625c'
down_revision = '5468fe84a8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credential', schema=None) as batch_op:
        batch_op.drop_index('ix_user_credential_firebase_uid')
        batch_op.drop_index('ix_user_credential_email')
        batch_op.create_index(batch_op.f('ix_user_credential_email'), ['email'], unique=True)
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_credential_email'))
        batch_op.create_index('ix_user_credential_email', ['email'], unique=False)
        batch_op.create_index('ix_user_credential_firebase_uid', ['firebase_uid'], unique=True)

    # ### end Alembic commands ###
