name: Security Scan

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit pip-audit

      - name: Run Bandit
        run: |
          echo "Running Bandit..."
          bandit -r . -f txt -o bandit-results.txt || true

      - name: Run pip-audit
        run: |
          echo "Running pip-audit..."
          pip-audit -r requirements.txt > pip-audit-results.txt || true

      - name: Combine results
        run: |
          echo "🔒 Security Scan Results" > security-scan-results.txt
          echo "=========================" >> security-scan-results.txt

          echo "" >> security-scan-results.txt
          echo "📘 Bandit Scan:" >> security-scan-results.txt
          echo "-------------------" >> security-scan-results.txt
          cat bandit-results.txt >> security-scan-results.txt

          echo "" >> security-scan-results.txt
          echo "📦 pip-audit:" >> security-scan-results.txt
          echo "-------------------" >> security-scan-results.txt
          cat pip-audit-results.txt >> security-scan-results.txt

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            security-scan-results.txt
            bandit-results.txt
            pip-audit-results.txt
          retention-days: 5

      - name: Create PR comment body
        id: comment_body
        run: |
          echo 'comment<<EOF' >> $GITHUB_ENV
          echo '## 🔒 Security Scan Summary' >> $GITHUB_ENV
          echo '' >> $GITHUB_ENV
          echo '```' >> $GITHUB_ENV
          cat security-scan-results.txt >> $GITHUB_ENV
          echo '```' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Post Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ env.comment }}
